### ISSUE TITLE
More powerful repository config

### ISSUE THREAD

**Issue by salim-b** [gethyas/doks-core#57]
Currently, the variable parts for the "Edit this page on ..." and "Last edited on ..." functionality are supposed to be defined via keys `repoHost` and `docsRepo*` in [`site.Data.doks`](https://github.com/gethyas/create-hyas/blob/2c67159557b326d8edbdf3c10b8f42bfdc5a0e64/template-doks/config/_default/hyas/doks.toml#L60-L66). Although this suggests that Doks would work with a lot of different forges (GitHub, GitLab, Gitea etc. pp.), it actually doesn't. This is because the [current template](https://github.com/gethyas/doks-core/blob/main/layouts/partials/main/edit-page.html) hardcodes an incomplete implementation how forge URLs are constructed. Currently, it is e.g. broken for GitLab.

I suggest to switch to a more elegant approach by allowing to configure the URL construction scheme directly in the config. A full example how this can be done is found in [this great post](https://discourse.gohugo.io/t/hugo-v0-112-0-new-template-functions/44512) on the Hugo forum. The example only misses the subdirectory part (currently encoded in `docsRepoSubPath`), besides it should be adaptable pretty-much 1:1 on Doks.

**Comment by james-d-elliott** [comment]
I'm taking this up, and I'm going to implement the pattern formatting. Can you however describe what the issue with the current URL is and are you using GitLab self-hosted or GitLab cloud?

**Comment by salim-b** [comment]
Sorry, I must have gotten confused. GitLab works fine with the current template. I guess I mistakenly thought GitLab subgroups like `gitlab.com/maingroup/subgroup/project` wouldn't work with the current solution, but they actually do.

But there's still an issue with the current template that the [one from Joe Mooring](https://discourse.gohugo.io/t/hugo-v0-112-0-new-template-functions/44512) does not suffer from (since it uses [`.File.Filename`](https://gohugo.io/methods/page/file/#filename) instead of [`File.Path`](https://gohugo.io/methods/page/file/#path)): If language-specific content is not stored in lang-subdirs but in files with the language code as suffix like `content/index.fr.md`, the URLs constructed by Doks current template are wrong. Joe Mooring's solution is always right.

I just tested it with the following three files changed to:

#### `config/_default/params.toml`

```toml
[repo]
  url = "https://gitlab.com/votelog/websites/votelog.ch"
  host =  "GitLab"
  branch = "main"
  path = "" # path from repo root; only if Hugo project is under subdir
  [repo.pattern]
    commit = '/commit/%s' # var = commit hash
    edit = '/edit/%s/%s' # 1st var  = `branch`, 2nd var = `path`
    view = '/blob/%s/%s' # 1st var  = `branch`, 2nd var = `path`
```

#### `layouts/partials/main/edit-page.html`

```html
{{- with .File }}
  {{- $file := . }}
  {{- with site.Params.repo }}
    {{- $filePathRel := strings.TrimPrefix hugo.WorkingDir $file.Filename }}
    {{- $href := urls.JoinPath .url .path (printf .pattern.edit .branch $filePathRel) }}
    <div class="edit-page">
      <a href="{{ $href }}" rel="external">
        <svg xmlns="http://www.w3.org/2000/svg" width="16" height="16" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round" class="feather feather-edit-2">
          <path d="M17 3a2.828 2.828 0 1 1 4 4L7.5 20.5 2 22l1.5-5.5L17 3z"></path>
        </svg>
        {{ i18n "edit_page" }} {{ .host }}
      </a>
    </div>
  {{- end }}
{{- end -}}
```

#### `layouts/partials/main/last-modified.html`

```html
{{ if .GitInfo -}}
  {{ with site.Params.repo -}}
    {{- $date := partial "main/date" (dict "Date" $.GitInfo.AuthorDate.Local "Format" $.Site.Params.BookDateFormat) -}}
    <div class="last-modified">
      <a href="{{ urls.JoinPath .url .path (printf .pattern.commit $.GitInfo.Hash)  }}">
        <svg xmlns="http://www.w3.org/2000/svg" width="16" height="16" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round" class="feather feather-calendar"><rect x="3" y="4" width="18" height="18" rx="2" ry="2"></rect><line x1="16" y1="2" x2="16" y2="6"></line><line x1="8" y1="2" x2="8" y2="6"></line><line x1="3" y1="10" x2="21" y2="10"></line></svg>
        {{ i18n "last_updated" }} {{ $date }}
      </a>
    </div>
  {{ end -}}
{{ end -}}
```

**Comment by james-d-elliott** [comment]
Yeah the GitLab links looked fine to me too but I think in general this is a good idea. and appreciate the insight.

I'd ideally prefer to prevent a change which breaks existing users without warning and allow for the backwards compatibility.

**Comment by james-d-elliott** [comment]
Also are you saying you confirm this works with the langs in subfolders too?

**Comment by salim-b** [comment]
> Also are you saying you confirm this works with the langs in subfolders too?

Yes.

> I'd ideally prefer to prevent a change which breaks existing users without warning and allow for the backwards compatibility.

Sure, I understand. Note that subpaths are still supported with the above (by setting `repo.path`). The template code could be made more robust for the case when part of the whole `repo` config is unset, though. Backwards compatibility *config*-wise I would advise against since that would result in ugly template code.

**Comment by james-d-elliott** [comment]
Can you give this a try when you get a chance to see there isn't anything obvious missed?

```toml
[doks]
  editPage = true # false (default) or true
  lastMod = true # false (default) or true
  
  ## Edit Link Generation Options. The 'repoHost' option sets a default 'repoURLPattern'.
  repoHost = "GitHub" # GitHub (default), Gitea, GitLab, Bitbucket, or BitbucketServer
  ## The format string override to build the edit URL. First parameter is docsRepo, second is docsRepoBranch, and third is the file path (prefixed with docsRepoSubPath if set). The format defaults are GitHub is '%s/blob/%s/%s', Gitea is '%s/_edit/%s/%s', GitLab is '%s/~blob/%s/%s', Bitbucket is '%s/src/%s/%s', BitbucketServer is '%s/browse/%s/%s'. This setting overrides these.
  repoURLPattern = "" # The URL pattern to override the repoHost for link generation. Format requires 3 string 
  docsRepo = "https://github.com/authelia/authelia"
  docsRepoBranch = "master" # main (default), master, or <branch name>
  docsRepoSubPath = "" # "" (none, default) or <sub path>
```

```html
{{ $pattern := site.Params.doks.repoURLPattern | default "" }}
{{ if not $pattern }}
  {{ if (eq site.Params.doks.repoHost "GitHub") }}
    {{ $pattern = "%s/blob/%s/%s" }}
  {{ else if (eq site.Params.doks.repoHost "Gitea") }}
    {{ $pattern = "%s/_edit/%s/%s" }}
  {{ else if (eq site.Params.doks.repoHost "GitLab") }}
    {{ $pattern = "%s/~blob/%s/%s" }}
  {{ else if (eq site.Params.doks.repoHost "Bitbucket") }}
    {{ $pattern = "%s/src/%s/%s" }}
  {{ else if (eq site.Params.doks.repoHost "BitbucketServer") }}
    {{ $pattern = "%s/browse/%s/%s" }}
  {{ end }}
{{ end }}

{{ $path := strings.TrimPrefix "/" (replace (strings.TrimPrefix hugo.WorkingDir .File.Filename) "\\" "/") }}

{{ $url := "" }}

{{ if and (isset .Site.Params.doks "docsreposubpath") (not (eq site.Params.doks.docsRepoSubPath "")) }}
  {{ $url = printf $pattern site.Params.doks.docsRepo site.Params.doks.docsRepoBranch (path.Join site.Params.doks.docsRepoSubPath $path) }}
{{ else }}
  {{ $url = printf $pattern site.Params.doks.docsRepoBranch $path }}
{{ end }}

<div class="edit-page">
  <a href="{{ $url }}">
    <svg xmlns="http://www.w3.org/2000/svg" width="16" height="16" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round" class="feather feather-edit-2">
      <path d="M17 3a2.828 2.828 0 1 1 4 4L7.5 20.5 2 22l1.5-5.5L17 3z"></path>
    </svg>
    {{ i18n "edit_page" }} {{ site.Params.doks.repoHost }}
  </a>
</div>
```
